server {
  listen 80;
  server_name _;

  # Frontend Vue: Se reenvía al contenedor "frontend"
  location / {
    proxy_pass           http://frontend:80/;
    proxy_set_header     Host $host;
    proxy_set_header     X-Real-IP $remote_addr;
    proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Ruta de catalogo
    # Ruta de inventario
    location /api/inventario/ {
      proxy_pass          http://inventario:5000/;
      proxy_set_header    Host $host;
      proxy_set_header    X-Real-IP $remote_addr;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }

  # Ruta de catalogo
  location /api/catalogo/ {
    proxy_pass          http://catalogo:5000/;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Ruta de clientes
  location /api/clientes/ {
    proxy_pass          http://clientes:5000/;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Ruta de pedidos
  location /api/pedidos/ {
    proxy_pass          http://pedidos:5000/;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  
  # Ruta de reportes
  location /api/reportes/ {
    proxy_pass          http://reportes:5000/;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
